services:
  db:
    image: 'postgres:latest'
    platform: 'linux/amd64'
    ports:
      - '7071:5432'
    environment:
      - POSTGRES_DB=rentaldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=StrongRoot1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: RentalDatabase
    restart: unless-stopped
    networks:
      - rental-net

volumes:
  postgres_data:
    driver: local

networks:
  rental-net:
    name: rental-network